### ISSUE TITLE
Hardcoded URL in plex.js

### ISSUE THREAD

**Issue by JamynShanley** [my-ugly-code/WebsUpTV#6]
https://github.com/my-ugly-code/WebsUpTV/blob/65b4ba7f9f31f5b3af4cda1f255e0776e5c51e09/services/plex.js#L72

Perhaps this should be updated to [use a variable](https://github.com/my-ugly-code/WebsUpTV/blob/65b4ba7f9f31f5b3af4cda1f255e0776e5c51e09/services/plex.js#L103).

**Comment by my-ugly-code** [comment]
@JamynShanley You're 100% right. I'll get this changed now. Thanks so much for letting me know!

**Comment by my-ugly-code** [comment]
On further inspection, the pipUrl field was a remnant of an older solution, which used the actual PMS details page instead of the node-hosted page. I've removed the unused field and pushed a new version of plex.js to the repo. Users do not need to update, but this will keep future changes cleaner. Thanks again, marking this as closed.
https://github.com/my-ugly-code/WebsUpTV/commit/4429ea3231812acd05ed859a17fd6fcc67bf8748
